resources/views/dopetrope/partials/main/blog.blade.php
=> Resolución del problema en el commit de Manuel y Martín

app/Http/Controllers/CatalogController.php, app/Models/Proyecto.php, database/migrations/2023_11_29_000000_create_proyectos_table.php, database/seeders/DatabaseSeeder.php, resources/views/catalog/index.blade.php, tests/Feature/ProyectosDBTest.php
En CatalogController le he añadido un id+1 al putEdit y al getEdit para que saliera la información correcta pero si lo hacía con el getShow no me pasa el test, por lo que la información que sale ahí no es del todo correcta.
=> Ejercicio_Base_de_Datos_4.7

resources/views/catalog/index.blade.php
=> closes #213

resources/views/partials/navbar.blade.php
=> Enlaces de usuario en el Navbar

app/Http/Controllers/CatalogController.php, app/Models/Proyecto.php, resources/views/catalog/show.blade.php, routes/web.php
Para el Issue #298 
No está completo, he solucionado ese error pero no consigo que me saque el show de los nuevos proyectos
(He comprobado que se me crean en la base de datos)
=>  Error en Catalog/create #298 

app/Http/Controllers/CatalogController.php
#300  issue solucionado con ayuda de Jesús.
=> Arreglo para poder editar proyectos

app/Http/Controllers/CatalogController.php, app/Models/Proyecto.php, resources/views/catalog/edit.blade.php, resources/views/catalog/show.blade.php, resources/views/dopetrope/partials/footer/ultimos.blade.php, resources/views/partials/navbar.blade.php, routes/web.php
Hecho el issue #216 
Se modifica tambien CatalogController para que mande los docentes a la vista
=> Vista edit modificada junto a CatalogController

app/Http/Controllers/CatalogController.php, database/migrations/2023_12_16_074209_add_fichero_to_proyectos_table.php, resources/views/catalog/edit.blade.php, resources/views/catalog/index.blade.php, resources/views/catalog/show.blade.php
Al hacer test hay que asegurarse de tener el enlace simbólico a public/storage, y tener una carpeta llamada: `marcapersonalFP23_24/storage/app/public/ficheros/`
=> Subir Fichero Comprimido a Proyectos (issue #226)

app/Http/Controllers/CurriculoController.php, resources/views/curriculos/index.blade.php, resources/views/curriculos/show.blade.php
=> Datos del estudiante asociado al currículo. #221

app/Http/Controllers/CurriculoController.php, app/Models/Curriculo.php, database/migrations/2023_12_15_000001_add_pdf_curriculo_to_curriculo_table.php, database/migrations/2023_12_15_000002_eliminar_columna_texto_curriculo.php, database/seeders/CurriculosTableSeeder.php, resources/views/curriculos/create.blade.php, resources/views/curriculos/edit.blade.php, resources/views/curriculos/show.blade.php, routes/web.php
Borrado de texto de currículo. Ahora se puede asociar un pdf del currículo a la hora de crear uno y también al editarlo. #286
=> Poder asociar un pdf al currículo #286

app/Http/Controllers/CatalogController.php, public/dopetrope/assets/css/main.css, resources/views/catalog/show.blade.php, routes/web.php
Issue #217 hecho (Hice un nuevo issue por un problema con los commits)
=> Funcionalidad aprobar o suspender proyecto

resources/views/curriculos/create.blade.php, resources/views/curriculos/edit.blade.php
=> Solución issue reabierto Videocurrículo #287 

resources/views/curriculos/index.blade.php
Solo he cambiado en la url de la imagen el id, que sea el de la base de datos.
=> Añadido miniatura del videocurriculum (issue #289)

resources/views/curriculos/index.blade.php
=> ID eliminado

resources/views/dopetrope/partials/header/intro.blade.php
=> Margenes añadidos en los divs de los iconos

resources/views/actividades/edit.blade.php, resources/views/catalog/edit.blade.php, resources/views/curriculos/edit.blade.php, resources/views/reconocimientos/edit.blade.php
=> solucion issue #288

app/Http/Controllers/ReconocimientoController.php, database/migrations/2023_12_16_000001_add_nombre_to_actividades_table.php, database/migrations/2023_12_17_000001_add_fecha_to_reconocimientos_table.php, database/seeders/ActividadesTableSeeder.php, database/seeders/ReconocimientosTableSeeder.php, resources/views/reconocimientos/index.blade.php, resources/views/reconocimientos/show.blade.php, routes/web.php
Issue #297
Comprobación de la validación:
En la semilla para rellenar los datos de la BBDD, creamos un reconocimiento sin docente_validador:
Registramos un  nuevo usuario (para tener un usuario logueado).
Comprobamos que se ha registrado correctamente:
Nos dirigimos a ese reconocimiento (con docente_validador null) y comprobamos que efectivamente aparece el botón validar:
Hacemos click en validar, y en la columa docente_validador, se debe haber añadido el id del usuario actual (luis con id=12):
=> Issue297 Datos del reconocimiento.

resources/views/dopetrope/partials/main.blade.php
=> Títulos index con mayúscula

resources/views/dopetrope/partials/footer/ultimos.blade.php
=> Enlace de los mejores proyectos del footer

resources/views/catalog/create.blade.php, resources/views/catalog/edit.blade.php
Aparte de eliminar los elementos duplicados de la vista edit, he hechos algunos pequeños cambios tanto en esta vista de edit como en la de create.
He bloqueado los TextArea para que no se puedan redimensionar manualmente al pinchar sobre ellos, y he espaciado los elementos con /br
=> Issue #343 Eliminados los duplicados de edit catalog

app/Http/Controllers/ProfileController.php, resources/views/profile/edit.blade.php, resources/views/profile/partials/update-curriculo-information-form.blade.php
=> edicion del curriculo profile

.env.example, resources/views/dopetrope/left-sidebar.blade.php, resources/views/dopetrope/master.blade.php, resources/views/dopetrope/no-sidebar.blade.php, resources/views/dopetrope/right-sidebar.blade.php, resources/views/layouts/app.blade.php, resources/views/welcome.blade.php
Hay que cambiar también el .env
=> Cambio dope trope

app/Providers/AppServiceProvider.php, resources/views/dopetrope/partials/footer.blade.php
#353 
Se crea una variable global en AppServiceProvider que podremos reutilizar en otras vistas
=> Añadido numero registros en el footer

app/Models/Proyecto.php, resources/views/dopetrope/partials/footer.blade.php
=> añadido el número de proyectos al footer

resources/views/dopetrope/partials/footer.blade.php
Arreglos de algunos estilos del footer.
=> Arreglo de los estilos del footer

resources/views/dopetrope/partials/footer/ultimos.blade.php, resources/views/dopetrope/partials/main/blog.blade.php
Modificado el texto de los botones de la home(Continue reading...)  y un título del footer.
=> Modificación de algunos textos

resources/views/profile/partials/update-profile-information-form.blade.php
El nombre y los apellidos en la vista profile/edit no aparecían, ahora sí.
=> Nombre y apellidos en el profile

app/Http/Controllers/ProfileController.php, database/seeders/ActividadesTableSeeder.php, resources/views/profile/edit.blade.php, resources/views/profile/partials/information-insignias.blade.php
Incluyen los cambios introducidos por Manuel, Raúl y Sergio
=> Insignias en profile

resources/views/catalog/index.blade.php
Los proyectos en la vista index ahora llevan al show de cada uno.
=> Enlaces de proyectos en la vista index

resources/js/Pages/users.jsx, resources/js/react-admin/App.tsx
=> Modificando las vistas de la tabla users

app/Http/Controllers/API/ActividadController.php, app/Http/Resources/ActividadResource.php, app/Models/Actividad.php, routes/api.php
=> Controlador de recursos de actividades

app/Http/Controllers/API/CurriculoController.php, app/Http/Resources/CurriculoResource.php, routes/api.php
=> Completada creacion de controlador API

app/Http/Controllers/API/ProyectoController.php, app/Http/Resources/ProyectoResource.php, routes/api.php
=> Creación de los endpoints de proyectos

app/Http/Controllers/API/UserController.php, app/Http/Resources/UserResource.php, routes/api.php
=> Creado el controlador de recursos de users

app/Helpers/FilterHelper.php, app/Http/Controllers/API/ActividadController.php, app/Http/Controllers/API/CicloController.php, app/Http/Controllers/API/CurriculoController.php, app/Http/Controllers/API/FamiliaProfesionalController.php, app/Http/Controllers/API/ProyectoController.php, app/Http/Controllers/API/ReconocimientoController.php, app/Http/Controllers/API/UserController.php, app/Http/Middleware/ReactAdminResponse.php
=> Conteo de filas filtradas

app/Http/Controllers/API/CompetenciasController.php, app/Http/Resources/CompetenciasResource.php, app/Models/Competencias.php, app/Models/Competencias_Actividades.php, database/factories/CompetenciasFactory.php, database/migrations/2024_01_22_000000_create_competencias_table.php, database/migrations/2024_01_22_082359_create_competencias_actividades_table.php, database/seeders/CompetenciasTableSeeder.php, database/seeders/DatabaseSeeder.php, resources/js/react-admin/App.tsx, resources/js/react-admin/Pages/Competencias.jsx, routes/api.php
(se me ha apagado el pc al final y he perdido los últimos cambios)
#484
=> Competencias #484

app/Http/Controllers/API/CompetenciaController.php, app/Http/Controllers/API/UserCompetenciaController.php, app/Http/Resources/CompetenciaResource.php, app/Http/Resources/UserCompetenciaResource.php, app/Models/Competencia.php, app/Models/UserCompetencia.php, database/factories/CompetenciaFactory.php, database/factories/UserCompetenciaFactory.php, database/migrations/2024_01_22_000000_create_competencias_table.php, database/migrations/2024_01_22_000000_create_users_competencias_table.php, database/seeders/CompetenciasTableSeeder.php, database/seeders/DatabaseSeeder.php, database/seeders/UsersCompetenciasTableSeeder.php, resources/js/react-admin/App.tsx, resources/js/react-admin/Pages/Competencias.jsx, routes/api.php
=> Competencias

app/Models/User_ciclo.php, database/migrations/2024_01_23_072505_users_ciclos_create_table.php, database/seeders/DatabaseSeeder.php, database/seeders/Users_ciclosTableSeeder.php
=> añadido todo lo necesario para el funcionamiento de la tabla users_ciclos

app/Models/ParticipanteProyecto.php, database/factories/ParticipanteProyectoFactory.php, database/migrations/2024_01_23_000000_create_participantes_proyectos_table.php, database/seeders/DatabaseSeeder.php, database/seeders/ParticipantesProyectosTableSeeder.php
=> Participantes Proyectos

app/Http/Controllers/API/IdiomaController.php
=> Arreglo al filtrar valores en la tabla Idiomas

app/Http/Resources/UserResource.php, app/Models/Competencia.php, app/Models/User.php
=> relacion users y competencias Arturo

app/Http/Resources/UserResource.php, app/Models/Proyecto.php, app/Models/User.php
Añadida la relacion entre users y proyectos
=> Propuesta solucion al issue "Relaciones users - proyectos #527"

app/Http/Resources/UserResource.php, app/Models/Actividad.php, app/Models/User.php
=> Relación user-actividades definida

app/Http/Resources/UserResource.php, app/Models/Actividad.php, app/Models/Reconocimiento.php, app/Models/User.php
=> Relación users-actividades

app/Http/Resources/ActividadResource.php, app/Models/Actividad.php, app/Models/Competencias.php, database/migrations/2024_01_22_082359_create_competencias_actividades_table.php
=> Relacion competencia actividad

app/Http/Resources/ActividadResource.php, app/Models/Actividad.php, app/Models/Reconocimiento.php
=> Relacion entre Actividades y Reconocimientos 1:N

app/Http/Resources/UserResource.php
=> Idiomas Formateados

app/Http/Controllers/API/CurriculoController.php, app/Models/Curriculo.php, database/migrations/2024_01_26_144900_add_sobre_mi_to_curriculos_table.php, database/seeders/CurriculosTableSeeder.php, resources/js/react-admin/Pages/Curriculos.jsx
=> Atributo sobre_mi curriculos

database/migrations/2024_01_22_072456_create_idiomas_table.php, database/seeders/IdiomasTableSeeder.php
=> Idiomas Oficiales terminado

app/Http/Controllers/API/CountController.php, routes/api.php
=> Endpoint para obtener total registros de una tabla

app/Http/Resources/ProyectoResource.php, app/Models/Proyecto.php
=> Issue nombre docente

database/migrations/2024_01_22_000000_create_users_competencias_table.php, database/seeders/UsersCompetenciasTableSeeder.php
He añadido control de duplicados para las competencias #559
=> issue completado

database/migrations/2024_01_22_000000_create_users_competencias_table.php, database/seeders/UsersCompetenciasTableSeeder.php
=> seed users_competencias Arturo

app/Http/Controllers/API/IdiomaController.php, app/Models/Idioma.php, resources/js/react-admin/Pages/Idiomas.jsx
Lo he hecho rápido, si hay algun fallo intentare corregirlo antes del lunes
=> Cambiado la visualizacion de la tabla idioma de react admin

database/seeders/ActividadesCompetenciasTableSeeder.php
=> Issue Seeder competencias-actividades

database/seeders/Users_ciclosTableSeeder.php
=> hecho el seeder de users_ciclos

app/Http/Controllers/API/ActividadController.php, app/Policies/ActividadPolicy.php, app/Providers/AuthServiceProvider.php
#609 A la hora de probarlo en react-admin, da error de autenticación, ya que, en la tabla actividades no existe user_id, si no docente_id, y el modelo User está buscando en la tabla dicha columna
=> Politicas y roles de Actividades

app/Http/Controllers/API/CicloController.php, app/Policies/CicloPolicy.php, app/Providers/AuthServiceProvider.php
=> Autorización a ciclos

app/Http/Controllers/API/CompetenciaController.php, app/Policies/CompetenciaPolicy.php, app/Providers/AuthServiceProvider.php
=> Policies Competencia

app/Http/Controllers/API/FamiliaProfesionalController.php, app/Http/Controllers/API/IdiomaController.php, app/Policies/FamiliaProfesionalPolicy.php, app/Policies/IdiomaPolicy.php, app/Providers/AuthServiceProvider.php
=> Ejercicios autorización Familias Profesionales Idiomas (Issue #613)

app/Http/Controllers/API/ProyectoController.php, app/Policies/ProyectoPolicy.php, app/Providers/AuthServiceProvider.php
=> Policy Proyecto

app/Http/Controllers/API/UserController.php, app/Policies/UsersPolicy.php, app/Providers/AuthServiceProvider.php
=> Autorizacion Users

app/Http/Controllers/API/ReconocimientoController.php, app/Policies/ReconocimientoPolicy.php, app/Providers/AuthServiceProvider.php
=> Policies de Reconocimientos

app/Http/Controllers/API/CurriculoController.php
=> Error de Nomenclatura solucionado

app/Http/Controllers/API/ProyectoController.php, app/Http/Resources/ProyectoResource.php, resources/js/react-admin/Pages/Proyectos.jsx, resources/js/react-admin/dataProvider.ts
También se tiene en cuenta el caso en el que se haya modificado el registro sin modificar el fichero.
=> El recurso devuelve attachements sin modificar el valor de fichero

app/Http/Controllers/API/UserController.php, app/Http/Resources/UserResource.php, app/Models/User.php, resources/js/react-admin/Pages/Users.jsx, resources/js/react-admin/authProvider.ts, resources/js/react-admin/dataProvider.ts
=> Añadir Avatar Mar

app/Http/Controllers/API/CurriculoController.php, app/Http/Resources/CurriculoResource.php, app/Models/Curriculo.php, app/Policies/CurriculoPolicy.php, resources/js/react-admin/Pages/Curriculos.jsx, resources/js/react-admin/dataProvider.ts, routes/api.php
=> EndPoint creado para descargar curriculo

.env.example, app/Http/Controllers/API/ProyectoController.php, app/Models/Proyecto.php, app/Providers/GitHubServiceProvider.php, database/migrations/2024_02_13_103845_add_url_github_to_proyectos_table.php
=> Modificar Proyecto para subir a Repositorio Comun

.env.example, app/Http/Controllers/API/ProyectoController.php, app/Models/Proyecto.php, app/Providers/GitHubServiceProvider.php, composer.json, composer.lock, database/migrations/2024_02_10_014401_add_url_github_to_proyectos_table.php, routes/api.php
=> Issue Medio Copiar a repositorio común

app/Http/Controllers/API/UserController.php, app/Models/Curriculo.php, app/Models/Reconocimiento.php, app/Models/User.php, database/seeders/CurriculosTableSeeder.php, database/seeders/ReconocimientosTableSeeder.php, resources/js/Pages/front/src/servicios/getAllAlumnos.jsx, routes/api.php
GET Estudiantes y Docentes además de Users
Especificando algunas claves ajenas en relaciones cuando se relacionan con estudiantes o docentes en lugar de users.
=> GET Estudiantes y Docentes además de Users

app/Http/Controllers/API/UserController.php, app/Http/Controllers/Auth/NewPasswordController.php, app/Http/Resources/ActividadResource.php, app/Models/User.php, resources/js/Pages/Auth/ResetPassword.jsx, resources/js/react-admin/Pages/Actividad.jsx, resources/js/react-admin/authProvider.ts, resources/js/react-admin/dataProvider.ts, routes/api.php
- Ajustando el reseteo de contraseña
- Utilizando permissions en react-admin
=> React admin register

resources/js/Pages/front/src/componentes/DropDownComponent.jsx, resources/js/react-admin/Pages/Ciclos.jsx, resources/js/react-admin/Pages/Idiomas.jsx, resources/js/react-admin/Pages/Proyectos.jsx, resources/js/react-admin/Pages/Users.jsx
Eliminando también el correo del listado y de export
=> Editando ciclos e idiomas desde perfil usuario
